### ISSUE TITLE
Includes are not to be watched

### ISSUE THREAD

**Issue by droooney** [aMarCruz/rollup-plugin-pug#3] opened 2016-09-26 07:53 UTC
If you use this plugin with rollup-watch (I don't know if it's related to this plugin or rollup-watch) the files you include are not to be watched. For example if you have:

``` pug
// main.pug
include ./mixins

+mixin(name)
```

``` pug
// mixins.pug

mixin mixin(name)
  div= name
```

and if you change `mixins.pug` the watch process does not reflect. Can you please look into that and tell if I should report the issue there (rollup-watch) or it's related to rollup-plugin-pug?

**Comment by aMarCruz** [comment] 2016-09-26 08:50
@droooney , I think this is related to optimizations in rollup's `watch` mode, as rollup don't know about "includes" in particular dialects. I don't know how trigger the rebuild without changing the main pug, maybe using `pug --watch` can help.

Anyway I'll take a look on this and how it was solved in other plugins.
Thanks for your feedback

**Comment by droooney** [comment] 2016-09-26 10:01
I've noticed the same thing in the less plugin. Maybe I should really report there (I mean, rollup-watch). How can I do something like `pug --watch` if I use rollup and this plugin?

PS: thanks for your work :)

**Comment by aMarCruz** [comment] 2016-09-26 15:20
@droooney yes, the problem is in rollup-watch optimization rebuilding only files w/changes.

I mean `pug --watch` instead rollup-watch for develop pug files but you're right, its a mess.

**Comment by aMarCruz** [comment] 2016-10-29 23:35
@droooney , just I push a new version of the plugin. It is a complete rewrite that ...
- import dependencies (pug extends and include directives)
- can pre-evaluate the templates to produce plain HTML
- does not need to install pug-runtime

This version is not in npm yet, we are not using rollup in current projects so I can't do heavy tests, but I think this must be working in watch mode now.

Please install from the repo and test it... I will publish it to npm if your tests pass.

**Comment by aMarCruz** [comment] 2016-11-01 01:20
Closing this issue now, if you have problems with v0.1.0 please reopen.

**Closed as completed by aMarCruz** 2016-11-01 01:20 UTC
